-- Add WhatsApp RSVP breakdown columns to FieldStat
ALTER TABLE "FieldStat" ADD COLUMN IF NOT EXISTS "location"  TEXT;
ALTER TABLE "FieldStat" ADD COLUMN IF NOT EXISTS "waIn"      INTEGER;
ALTER TABLE "FieldStat" ADD COLUMN IF NOT EXISTS "waPlus1"   INTEGER;
ALTER TABLE "FieldStat" ADD COLUMN IF NOT EXISTS "waPlus2"   INTEGER;
ALTER TABLE "FieldStat" ADD COLUMN IF NOT EXISTS "waMaybe"   INTEGER;
ALTER TABLE "FieldStat" ADD COLUMN IF NOT EXISTS "waOut"     INTEGER;
ALTER TABLE "FieldStat" ADD COLUMN IF NOT EXISTS "groupSize" INTEGER;
